server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: telemetry-store-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type:  com.zuehlke.telemetry.store.model.TelemetryData
        spring.json.use.type.headers: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/telemetry_db

kafka:
  topic:
    in: telemetry.processed